### PR TITLE
fix(Tag): adjust sizes on variants

### LINKED ISSUE #683: [Tag] Support multiple sizes
We are receiving design feedback to change the font size in one use case to `10px`, and in other use case, `14px`.

**Update:**

Each `kind` of Tag has slightly different dimensions and font size. That was the issue. Refer to Figma to make style updates.

### PR DESCRIPTION
**Pull request by akdetrick**
fixes #683 

Match variants to figma designs.

Screen Shot 2022-04-13 at 3 45 24 PM
Screen Shot 2022-04-13 at 3 45 19 PM
Screen Shot 2022-04-13 at 3 45 14 PM
Screen Shot 2022-04-13 at 3 45 09 PM

### CODE REVIEW

File: src/Tag/index.js [hunk 1]
```diff
@@ -25,6 +25,11 @@ const Tag = ({
               role="button"
               tabIndex={0}
               onClick={onDismiss}
+              onKeyUp={({ key }) => {
+                if (key === "Enter" || key == " ") {
```
Comment (akdetrick) [inline src/Tag/index.js:29]: the standard spacebar `key` being `" "` is just the silliest thing

**Review by pr-narmi — APPROVED** [review]
