### PR TITLE
fix(Dialog): add bottom spacing when no footer is passed in

### LINKED ISSUE #1002: [Dialog] Bottom spacing looks wrong after v3
### Component/Module
`Dialog`

### Screenshots (if applicable)
image

### PR DESCRIPTION
**Pull request by akdetrick**
closes #1002 

As part of the NDS v3 release, we refactored some components in `banking` that were using the deprecated `Modal` component. The `Modal` component was providing some bottom spacing to the content area. In `Dialog`, the `footer` prop causes some bottom padding to be added.

**This PR will add some default bottom padding to `Dialog` when no `footer` prop is passed in.**

### Examples

After the change, `Dialog` usage without a footer will have bottom spacing

Screen Shot 2023-08-18 at 3 20 46 PM
Screen Shot 2023-08-18 at 3 22 22 PM

### CODE REVIEW

File: src/Dialog/index.js [hunk 1]
```diff
@@ -100,7 +100,10 @@ const Dialog = ({
             </div>
             <div
               ref={contentRef}
-              className="nds-dialog-content nds-typography padding--top--xs"
+              className={cc([
+                "nds-dialog-content nds-typography padding--top--xs",
+                { "padding--bottom--l": !footer },
```
Comment (rogerioshieh) [inline src/Dialog/index.js:105]:
```suggestion
                { "padding--bottom--xl": !footer },
```

Should it be xl to match what we have on the footer? https://github.com/narmi/design_system/blob/29a3a61b0097a7c59dbc0e46bd0e302ad35a3c1b/src/Dialog/index.scss#L101

Otherwise LGTM

**Review by rogerioshieh — APPROVED** [review]
